theme: minima
title: Grass Cutter
author: TheEasyJC
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Do you cut your own grass? How long have you been cutting grass? Have you ever cut grass? What famous people do you think cut their own grass?

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
